server {
  listen 80;
  server_name _;
  client_max_body_size 100m;

  location /api/files {
    proxy_pass http://remote-storage:8080/files;
    proxy_http_version 1.1;
  }

  location /fonts/ {
    root /usr/share/nginx/html;
    add_header Access-Control-Allow-Origin "*" always;
    try_files $uri =404;
  }

  location / {
    root /usr/share/nginx/html;
    try_files $uri $uri/ /index.html;
  }
}
